
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game-7dtd-serverfiles
  labels:
    app: game-7dtd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
