apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-7dtd-server
  annotations:
    kubesailEditorUid: c835dc72-c037-4d2d-ae62-7c0cd6f47b9e
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: game-7dtd
  template:
    metadata:
      labels:
        app: game-7dtd
    spec:
      volumes:
        - name: world
          persistentVolumeClaim:
            claimName: game-7dtd-world

        - name: serverfiles
          persistentVolumeClaim:
            claimName: game-7dtd-serverfiles

        - name: logs
          persistentVolumeClaim:
            claimName: game-7dtd-logs

        - name: backups
          persistentVolumeClaim:
            claimName: game-7dtd-backups
        - name: alerts
          persistentVolumeClaim:
            claimName: game-7dtd-alerts
      containers:
        - name: game-7dtd
          image: vinanrra/7dtd-server
          imagePullPolicy: Always
          volumeMounts:
            - name: world
              mountPath: /home/sdtserver/.local/share/7DaysToDie/
          ports:
            - containerPort: 26900
              name: tcp-game
              hostPort: 26900
            - containerPort: 26901
              name: udp-game-2
              hostPort: 26901
              protocol: UDP
            - containerPort: 26902
              name: udp-game-3
              hostPort: 26902
              protocol: UDP
            - containerPort: 8080
              name: webadmin
              hostPort: 8080
            - containerPort: 8081
              name: telnet
              hostPort: 8081
            - containerPort: 8082
              name: webserver
              hostPort: 8082
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 4
              memory: 16Gi
