apiVersion: v1
kind: Service
metadata:
  name: 7dtd-server
spec:
  type: LoadBalancer
  ports:
    - containerPort: 26900
      hostPort: 26900
      type: TCP
    - containerPort: 26900
      hostPort: 26900
      type: UDP
    - containerPort: 26901
      hostPort: 26901
      type: UDP
    - containerPort: 26902
      hostPort: 26902
      type: UDP
    - containerPort: 8080
      hostPort: 8080
      type: TCP #OPTIONAL WEBADMIN
    - containerPort: 8081
      hostPort: 8081
      type: TCP #OPTIONAL TELNET
    - containerPort: 8082
      hostPort: 8082
      type: TCP #OPTIONAL WEBSERVER https://7dtd.illy.bz/wiki/Server%20fixes
  selector:
    app: 7dtd