apiVersion: v1
kind: Service
metadata:
  name: game-7dtd-server
spec:
  type: NodePort
  ports:
    - port: 26900
      targetPort: 26900
      name: tcp-game-1
      protocol: TCP

    - port: 26901
      targetPort: 26901
      name: udp-game-2
      protocol: UDP

    - port: 26902
      targetPort: 26902
      name: udp-game-3
      protocol: UDP

    - port: 8080
      targetPort: 8080
      name: webadmin
      protocol: TCP

    - port: 8081
      targetPort: 8081
      name: telnet
      protocol: TCP

    - port: 8082
      targetPort: 8082
      name: webserver
      protocol: TCP
  selector:
    app: game-7dtd
